//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Feedback
    {
        [Key]
        public int feedbackId { get; set; }

        [Required(ErrorMessage = " Feedback is Required")]
        public string feedbackString { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> responsderId { get; set; }
    
        public virtual Responder Responder { get; set; }
        public virtual User User { get; set; }
    }
}
