//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        

        
        public int questionId { get; set; }
        public int optionId { get; set; }
        public int responseId { get; set; }
        public Nullable<int> responderId { get; set; }
    
        public virtual Responder Responder { get; set; }

        

    }
}
